config/routes.rb
Rails.application.routes.draw do
  #get 'robots/index'
  #get 'robots/new'
  #get 'robots/update'
  #get 'robots/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :robots
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/armor.rb
class Armor < ApplicationRecord
	belongs_to :robots, required: true

	validates :a_type, presence: true, inclusion: { in: ["shield", "magnetic field", "invisible field"]}
  	validates :serial_number, format: { with: /\AA+\d{6}\z/}
end

app/models/robot.rb
class Robot < ApplicationRecord
	has_many :armors
	has_many :weapons


  	validates :name, presence: true, uniqueness: true
  	validates :r_type, presence: true, inclusion: { in: %w(hackerobot protectrobot tacticrobot),
    	message: "%{value} is not a valid type" }
  	validates :serial_number, format: { with: /\AR+\d{6}\z/, 
    	message: "Please enter keywords in correct format (letter (R) + 6 digits)"}
end

app/models/weapon.rb
class Weapon < ApplicationRecord
	belongs_to :robots, required: true

	validates :weapon_type, presence: true, inclusion: { in: %w(laser code acid map)}
  	validates :serial_number, format: { with: /\AW+\d{6}\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

	before_action :set_robot, only: [:show, :edit, :update, :destroy]

  def index
  	@robots = Robot.all
  	#if @robots.empty? 
  		#return "No hay robots"
  	#else
  		#@robots
  	#end
  end

  def show 
  end

  def new 
  	@robot=Robot.new
  end

  def create

  	@robot=Robot.new(robots_params)
  	if @robot.save
      	#render :index
        render :show, notice: 'robot was successfully created.' 
        
      else
         render "new"
    end
    
  end

  def edit
  end

  def update

    if @robot.update(robots_params)
      redirect_to @robot
    else
      render 'edit'
    end
    
  end


  def destroy
  	@robot.destroy
    redirect_to robots_path
  end

  private

  def set_robot
    @robot = Robot.find(params[:id])

  end

  def robots_params

  	params.require(:robot).permit(:name,:serial_number, :r_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrobot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/_form.html.erb
<%= form_for @robot do |f| %>
	Name: <%= f.text_field :name %><br>
	Type: <%= f.text_field :r_type %><br>
	Serial Number: <%= f.text_field :serial_number %><br>
	<%= f.submit %>

<% end %>
<%= link_to "Index", robots_path %>

app/views/robots/edit.html.erb
<h1>Robots#update</h1>

<%= render 'form'  %>

app/views/robots/index.html.erb
<h1>Robots</h1>
<table>
	<tr><th><b>Name </b></th><th><b> Type</b></th><th><b>Serial Number</b></th></tr>
	<% @robots.each do |values| %>
			<tr>
				<td><%=values.name%></td>
				<td><%=values.r_type%></td>
				<td><%=values.serial_number%></td>
				<td><%= link_to 'Edit', edit_robot_path(values) %></td>
				<td><%= link_to 'Destroy', robot_path(values), method: :delete %></td>
				
			</tr>
			
	<% end %>
</table>
<%= link_to "New Robot" ,new_robot_path %>

app/views/robots/new.html.erb
<h1>Robots new</h1>

<%= render 'form' %>

app/views/robots/show.html.erb
<h1>Robots show</h1>
<p>
  <strong>Name:</strong>
  <%= @robot.name %>
</p>
 <p>
  <strong>Robot type:</strong>
  <%= @robot.r_type %>
</p>
<p>
  <strong>Serial  number:</strong>
  <%= @robot.serial_number %>
</p>
<%= link_to "Index" ,robots_path %>